esphome:
  name: espatom-mtec-w3
  friendly_name: espatom-mtec-w3
  includes: []
  libraries:
    - Wire
    - EspSoftwareSerial

external_components:
  - source: 
      type: local
      path: components
    components: [tdr_soil_sensor2]

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "EugYrZ/eclMTm+t7XbVBVPOkH8a6y7AsaoYsOU13AlU="

ota:
  password: "5bfed4c71fb49043901bb40d5dcd0d58"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Espatom-Mtec-W3 Fallback Hotspot"
    password: "TEd58jBMOdmh"

captive_portal:

### RS485
uart:
  id: modbus_serial
  rx_pin: 1
  tx_pin: 2
  baud_rate: 4800
  stop_bits: 1

modbus:
  id: modbus1
  uart_id: modbus_serial

modbus_controller:
  - id: con_modbus_name
    update_interval: 11s
    address: 0x1
    command_throttle: 150ms
    setup_priority: -10

# TDR Soil Sensor 
tdr_soil_sensor2:
  - id: TDR0
    wc:
      id: WC
      name: "Moisture WC"
      address: 0x0000
      unit_of_measurement: "%"
      accuracy_decimals: 1
      state_class: measurement
    temperature:
      id: Temp
      name: "Soil temp"
      address: 0x0001
      unit_of_measurement: "°C"
      accuracy_decimals: 1
      state_class: measurement
    ec:
      id: EC
      name: "Conductivity 1 dS/m = 1 mS/cm"
      address: 0x0002
      unit_of_measurement: "dS/m" # Adjusted based on the name
      accuracy_decimals: 1
      state_class: measurement
    soil_temperature:
      name: "Soil Calibrated Temperature"
      unit_of_measurement: "°C"
      accuracy_decimals: 1
    soil_humidity:
      name: "Soil Calibrated Humidity"
      unit_of_measurement: "%"
      accuracy_decimals: 1
    soil_pw_ec:
      name: "Soil PW EC" # Removed redundant "soil"
      unit_of_measurement: "mS/cm" # Adjusted based on common units
      accuracy_decimals: 1
